spring.application.name=aws-service
server.port=8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

aws.bucket.name=fotoalpha-760661274759-eu-north-1-an
aws.region=eu-north-1
aws.credentials.secret-key=K6ol16RoJWW2jSphymd0iIJGdlQ+h0cpnTGzKJVC
aws.credentials.access-key=AKIA3CGXR6CD3GWBYUC

jwt.secret-key=yDE+Im6oxNAv3M+bi0IrWNWRWatNJdag1P2uVdWNxOo=