spring.application.name=portfolio-service
server.port=8082
eureka.client.service-url.defaultZone=${EUREKA_SERVER_DEFAULTZONE}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.url=${PORSERVICE_JDBC_URL:jdbc:postgresql://localhost:5433/PortfolioService}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=portfolio-service
spring.kafka.consumer.properties.spring.json.type.mapping=savePhotos:com.fotoalpha.portfolioservice.KafkaEvents.SavePhotosEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.fotoalpha.*
spring.kafka.consumer.auto-offset-reset=latest