spring.application.name=user-service
server.port=8088
jwt.secret.key=${JWT_SECRET_KEY_GEN}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.url=jdbc:postgresql://localhost:5433/UserService
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

